### ISSUE TITLE
Cannot download from NPM/Yarn

### ISSUE THREAD

**Issue by kevinhylant** [jkcorrea/airtable-typegen#39]
Hey @jkcorrea ,

First. Thank YOU!
So much. For putting the time into this project & packaging it up for others to use.

Unfortunately it looks like something in the configuration is corrupt and preventing it from being downloadable via NPM.

Any ideas?
Kevin

**Comment by jkcorrea** [comment]
Alas I admit, I didn't really test this package out much. Quickly realized I didn't need it for what I was building.

Is the problem happening when you `npm install`? It works on my end

**Comment by kevinhylant** [comment]
The problem happens when I try to install the package itself `yarn add -D airtable-typegen`

For the time being I actually ended up copying over all the bits of the code I need and got it working locally last night.
Considering that you won’t be managing this on an ongoing basis, and since I don’t have the capacity right now (yet) to managing a publicly-used package, perhaps this is the best approach anyhow.
- It also allowed me to update your configuration to generate types instead of interfaces so it plays more nicely with Airtable’s Record<TableType>.

But thank you again so much for building this & making my life so so much easier moving forward since I’d been manually typing everything.

**Comment by jessetinell** [comment]
Same here. Doesn't seem to exist on NPM: https://www.npmjs.com/search?q=airtable-typegen

**Comment by kevinhylant** [comment]
I ended up lifting the code out of this great work & adjusting it slightly to my needs and it has been working great. Thank you!

**Comment by jkcorrea** [comment]
Should be available again at https://www.npmjs.com/package/airtable-typegen
