### ISSUE TITLE
Maintenance Status

### ISSUE THREAD

**Issue by sheindel** [jkcorrea/airtable-typegen#51]
Hello! First of all, thank you so much for your work on this library! I manage a decently sized air table based mobile and web application and this is just exactly what I was looking for to get much better type safety and code completion of my existing air table classes.

I was wondering what the maintenance status of this repository was. I have some bug fixes that I implemented locally with this code base and I'm just wondering if I should open a PR or plan on forking and maintaining my own copy.

Thanks again for all the initial work! Super excellent!

**Comment by silicakes** [comment]
I was wondering the same thing.
Also, thank you for working on this!

**Comment by jkcorrea** [comment]
Hey all, wasn't checking this repo for a while, didnt know anyone was finding it useful.

Happy to actively maintain it and accept PRs now, let me know @sheindel @silicakes
